/**
 * FMAN720 / ALGO LOG — training widgets
 *
 * Renders, from /training-stats.json (generated by scripts/training-stats.js):
 *   1. Training panel (stats strip + GitHub-style heatmap) on the archives
 *      page (injected above the list) and on the about page (section 06).
 *   2. A late-night easter egg chip (00:00–04:59 local time) echoing the
 *      "deep-night review" persona. ?night=1 forces it on for preview.
 *
 * Vanilla JS, pjax-aware: re-runs on `pjax:complete`, mounts are idempotent.
 */

(function () {
  'use strict';

  var state = { data: null, promise: null };
  var chipTimer = null;

  function el(tag, cls, text) {
    var node = document.createElement(tag);
    if (cls) node.className = cls;
    if (text !== undefined && text !== null) node.textContent = text;
    return node;
  }

  function loadData() {
    if (state.data) return Promise.resolve(state.data);
    if (!state.promise) {
      state.promise = fetch('/training-stats.json', { cache: 'no-cache' })
        .then(function (res) { return res.json(); })
        .then(function (data) { state.data = data; return data; })
        .catch(function (err) {
          console.error('[training] failed to load training-stats.json:', err);
          state.promise = null;
          return null;
        });
    }
    return state.promise;
  }

  function dots(iso) {
    return iso ? iso.replace(/-/g, '.') : '';
  }

  /* ---------------- stats strip ---------------- */

  function buildStatsStrip(data) {
    var wrap = el('div', 'training-stats');
    var cells = [
      ['RECORDS', String(data.total), '训练记录'],
      ['LONGEST STREAK', data.streak.longest + ' 天', '最长连续更新'],
      ['RECENT 30D', String(data.recent30), '近 30 天新增'],
      ['ACTIVE DAYS', String(data.activeDays), '有训练的日子'],
    ];
    cells.forEach(function (c) {
      var cell = el('div', 'training-stats__cell');
      cell.appendChild(el('small', 'training-stats__en', c[0]));
      cell.appendChild(el('strong', 'training-stats__value', c[1]));
      cell.appendChild(el('span', 'training-stats__cn', c[2]));
      wrap.appendChild(cell);
    });

    var chips = el('div', 'training-stats__chips');
    (data.categoryOrder || []).forEach(function (key) {
      var count = (data.byOJ || {})[key] || 0;
      if (!count) return;
      var chip = el('span', 'training-stats__chip');
      chip.appendChild(el('span', 'training-stats__chip-label', (data.labels || {})[key] || key));
      chip.appendChild(el('b', 'training-stats__chip-count', String(count)));
      chips.appendChild(chip);
    });
    wrap.appendChild(chips);
    return wrap;
  }

  /* ---------------- heatmap ---------------- */

  var DAY_MS = 86400000;
  var CELL_PITCH = 7; // cells per column (one week)

  function levelOf(count) {
    if (count >= 4) return 4;
    if (count === 3) return 3;
    if (count === 2) return 2;
    if (count === 1) return 1;
    return 0;
  }

  function defaultCaption(data) {
    return '累计 ' + data.total + ' 篇 · 覆盖 ' + data.activeDays + ' 天 · 最长连续 ' + data.streak.longest + ' 天';
  }

  function buildHeatmap(data) {
    var wrap = el('div', 'training-heatmap');
    var head = el('div', 'training-heatmap__head');
    head.appendChild(el('span', 'training-heatmap__eyebrow', '// TRAINING HEATMAP'));
    head.appendChild(el('span', 'training-heatmap__meta',
      dots(data.firstDate) + ' — ' + dots(data.lastDate)));
    wrap.appendChild(head);

    var start = new Date(data.firstDate + 'T00:00:00Z');
    var firstData = new Date(data.firstDate + 'T00:00:00Z');
    var end = new Date(data.lastDate + 'T00:00:00Z');
    start.setUTCDate(start.getUTCDate() - start.getUTCDay()); // back to Sunday
    var totalDays = Math.round((end.getTime() - start.getTime()) / DAY_MS);

    var months = el('div', 'training-heatmap__months');
    var grid = el('div', 'training-heatmap__grid');
    grid.setAttribute('aria-hidden', 'true');

    for (var i = 0; i <= totalDays; i++) {
      var d = new Date(start.getTime() + i * DAY_MS);
      var iso = d.toISOString().slice(0, 10);
      var inRange = d.getTime() >= firstData.getTime();
      var count = data.days[iso] || 0;

      var cell = el('span', 'training-heatmap__cell');
      if (inRange) {
        cell.classList.add('training-heatmap__cell--lv' + levelOf(count));
        cell.title = iso + ' · ' + (count ? count + ' 篇' : '无训练');
        cell.dataset.date = iso;
        cell.dataset.count = String(count);
      } else {
        cell.classList.add('training-heatmap__cell--empty');
      }
      grid.appendChild(cell);

      if (d.getUTCDate() === 1) {
        var label = el('span', 'training-heatmap__month', (d.getUTCMonth() + 1) + '月');
        label.style.setProperty('--th-col', String(Math.floor(i / CELL_PITCH)));
        months.appendChild(label);
      }
    }

    var caption = el('span', 'training-heatmap__caption', defaultCaption(data));
    grid.addEventListener('mouseover', function (e) {
      var t = e.target;
      if (t && t.dataset && t.dataset.date) {
        var c = Number(t.dataset.count);
        caption.textContent = t.dataset.date + ' · ' + (c ? c + ' 篇训练' : '无训练记录');
      }
    });
    grid.addEventListener('mouseleave', function () {
      caption.textContent = defaultCaption(data);
    });

    var foot = el('div', 'training-heatmap__foot');
    var legend = el('span', 'training-heatmap__legend');
    legend.appendChild(el('span', 'training-heatmap__legend-text', '少'));
    for (var lv = 0; lv <= 4; lv++) {
      legend.appendChild(el('span', 'training-heatmap__cell training-heatmap__legend-cell training-heatmap__cell--lv' + lv));
    }
    legend.appendChild(el('span', 'training-heatmap__legend-text', '多'));
    foot.appendChild(legend);
    foot.appendChild(caption);
    var gridwrap = el('div', 'training-heatmap__gridwrap');
    gridwrap.appendChild(months);
    gridwrap.appendChild(grid);
    wrap.appendChild(gridwrap);
    wrap.appendChild(foot);
    return wrap;
  }

  /* ---------------- panel & mounts ---------------- */

  function buildPanel(data, variant) {
    var panel = el('div', 'training-panel training-panel--' + variant);
    var head = el('div', 'training-panel__head');
    head.appendChild(el('span', 'training-panel__eyebrow', '// TRAINING STATUS'));
    head.appendChild(el('strong', 'training-panel__title', '训练数据'));
    head.appendChild(el('span', 'training-panel__range',
      dots(data.firstDate) + ' → ' + dots(data.lastDate) + ' · 自动生成，随构建更新'));
    panel.appendChild(head);
    panel.appendChild(buildStatsStrip(data));
    panel.appendChild(buildHeatmap(data));
    return panel;
  }

  function mountArchives(data) {
    var shell = document.getElementById('archives-page');
    if (!shell || shell.dataset.trainingMounted === 'true') return;
    var panel = buildPanel(data, 'archive');
    shell.insertBefore(panel, shell.firstChild);
    shell.dataset.trainingMounted = 'true';
  }

  function mountAbout(data) {
    var mount = document.getElementById('training-dossier-mount');
    if (!mount || mount.dataset.trainingMounted === 'true') return;
    mount.appendChild(buildPanel(data, 'dossier'));
    mount.dataset.trainingMounted = 'true';
  }

  /* ---------------- late-night chip ---------------- */

  var NIGHT_MESSAGES = [
    '零点过了，今天的复盘写了吗？',
    '凌晨 1 点，思路还在的话就收个尾。',
    '凌晨 2 点还在卷，明天记得复盘。',
    '凌晨 3 点，身体是最大的 hack。',
    '快 5 点了，睡吧，题明天还在。',
  ];

  function pad2(n) {
    return String(n).padStart(2, '0');
  }

  function nightChip() {
    var now = new Date();
    var demo = /[?&]night=1/.test(location.search);
    var hour = now.getHours();
    var active = hour < 5 || demo;

    var chip = document.getElementById('training-night-chip');
    if (!active) {
      if (chip) chip.remove();
      if (chipTimer) { clearInterval(chipTimer); chipTimer = null; }
      return;
    }

    if (!chip && sessionStorage.getItem('trainingNightChipClosed') !== '1') {
      chip = document.createElement('div');
      chip.id = 'training-night-chip';
      chip.className = 'training-night-chip';
      chip.appendChild(el('span', 'training-night-chip__cursor', '>_'));
      chip.appendChild(el('span', 'training-night-chip__msg'));
      chip.appendChild(el('span', 'training-night-chip__time'));
      var close = el('button', 'training-night-chip__close', '×');
      close.type = 'button';
      close.setAttribute('aria-label', '关闭');
      close.addEventListener('click', function () {
        chip.remove();
        if (chipTimer) { clearInterval(chipTimer); chipTimer = null; }
        sessionStorage.setItem('trainingNightChipClosed', '1');
      });
      chip.appendChild(close);
      document.body.appendChild(chip);
      var show = function () { chip.classList.add('is-visible'); };
      requestAnimationFrame(function () { requestAnimationFrame(show); });
      setTimeout(show, 300); // fallback when rAF is throttled in background tabs
    }

    if (chip) {
      var idx = Math.min(Math.max(hour, 0), NIGHT_MESSAGES.length - 1);
      if (demo && hour >= 5) idx = 2;
      chip.querySelector('.training-night-chip__msg').textContent = NIGHT_MESSAGES[idx];
      chip.querySelector('.training-night-chip__time').textContent = pad2(now.getHours()) + ':' + pad2(now.getMinutes());
    }

    if (!chipTimer) {
      chipTimer = setInterval(function () {
        var c = document.getElementById('training-night-chip');
        if (!c) { clearInterval(chipTimer); chipTimer = null; return; }
        var t = new Date();
        if (t.getHours() >= 5 && !demo) { c.remove(); clearInterval(chipTimer); chipTimer = null; return; }
        c.querySelector('.training-night-chip__time').textContent = pad2(t.getHours()) + ':' + pad2(t.getMinutes());
      }, 30000);
    }
  }

  /* ---------------- boot ---------------- */

  function init() {
    loadData().then(function (data) {
      if (!data) return;
      mountArchives(data);
      mountAbout(data);
    });
    nightChip();
  }

  init();
  document.addEventListener('pjax:complete', init);
})();
